name: core_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  fl_chart: ^0.68.0
  get:
  dio: ^5.4.2+1
  logger: ^1.0.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_secure_storage: ^7.0.1
  file_picker: ^4.1.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  web_socket_channel: ^2.1.0
  flutter_dotenv: ^5.0.2
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.4+4
  flutter_json_viewer: ^1.0.1
  json_editor_flutter: ^1.4.2
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
    - .env
