name: core_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  fl_chart: ^0.68.0
  get:
  dio: ^5.4.2+1
  logger: ^2.4.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  file_picker:
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.0.2
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2
  flutter_json_viewer: ^1.0.1
  json_editor_flutter: ^1.4.2
  universal_platform: ^1.1.0
  firebase_database: ^11.0.4
  firebase_database_web: ^0.2.4
  permission_handler: ^11.3.1
  firebase_messaging:
  firebase_core: ^3.3.0
  cloud_firestore:
  qr_flutter: ^4.0.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
    - .env
